clc
clear

MCR = 5e6;

DF = 1;

rx = comm.SDRuReceiver(...
    'Platform', 'B210', ...
    'SerialNum', '31420EF', ...
    'CenterFrequency', 91.3e6, ...
    'Gain', 10, ...
    'MasterClockRate', MCR, ...
    'DecimationFactor', DF, ...
    'SamplesPerFrame', 362, ...
    'OutputDataType', 'double');

% Compute sample rate based on decimation
Fs = MCR / DF;

% Receive samples
disp('Receiving samples...');
data = rx(); % One frame
release(rx);

% Plot spectrum
spectrumAnalyzer = spectrumAnalyzer(...
    'SampleRate', Fs, ...
    'Title', 'Received Signal Spectrum', ...
    'Ce');
spectrumAnalyzer(data);